/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.apis

import com.xebia.functional.openai.model.CreateChatCompletionRequest
import com.xebia.functional.openai.model.CreateChatCompletionResponse
import java.io.IOException
import okhttp3.HttpUrl
import okhttp3.OkHttpClient
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.Success

class ChatApi(
  basePath: kotlin.String = defaultBasePath,
  client: OkHttpClient = ApiClient.defaultClient
) : ApiClient(basePath, client) {
  companion object {
    @JvmStatic
    val defaultBasePath: String by lazy {
      System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.openai.com/v1")
    }
  }

  /**
   * Creates a model response for the given chat conversation.
   *
   * @param createChatCompletionRequest
   * @return CreateChatCompletionResponse
   * @throws IllegalStateException If the request is not correctly configured
   * @throws IOException Rethrows the OkHttp execute method exception
   * @throws UnsupportedOperationException If the API returns an informational or redirection
   *   response
   * @throws ClientException If the API returns a client error response
   * @throws ServerException If the API returns a server error response
   */
  @Suppress("UNCHECKED_CAST")
  @Throws(
    IllegalStateException::class,
    IOException::class,
    UnsupportedOperationException::class,
    ClientException::class,
    ServerException::class
  )
  fun createChatCompletion(
    createChatCompletionRequest: CreateChatCompletionRequest
  ): CreateChatCompletionResponse {
    val localVarResponse =
      createChatCompletionWithHttpInfo(createChatCompletionRequest = createChatCompletionRequest)

    return when (localVarResponse.responseType) {
      ResponseType.Success -> (localVarResponse as Success<*>).data as CreateChatCompletionResponse
      ResponseType.Informational ->
        throw UnsupportedOperationException("Client does not support Informational responses.")
      ResponseType.Redirection ->
        throw UnsupportedOperationException("Client does not support Redirection responses.")
      ResponseType.ClientError -> {
        val localVarError = localVarResponse as ClientError<*>
        throw ClientException(
          "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
          localVarError.statusCode,
          localVarResponse
        )
      }
      ResponseType.ServerError -> {
        val localVarError = localVarResponse as ServerError<*>
        throw ServerException(
          "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
          localVarError.statusCode,
          localVarResponse
        )
      }
    }
  }

  /**
   * Creates a model response for the given chat conversation.
   *
   * @param createChatCompletionRequest
   * @return ApiResponse<CreateChatCompletionResponse?>
   * @throws IllegalStateException If the request is not correctly configured
   * @throws IOException Rethrows the OkHttp execute method exception
   */
  @Suppress("UNCHECKED_CAST")
  @Throws(IllegalStateException::class, IOException::class)
  fun createChatCompletionWithHttpInfo(
    createChatCompletionRequest: CreateChatCompletionRequest
  ): ApiResponse<CreateChatCompletionResponse?> {
    val localVariableConfig =
      createChatCompletionRequestConfig(createChatCompletionRequest = createChatCompletionRequest)

    return request<CreateChatCompletionRequest, CreateChatCompletionResponse>(localVariableConfig)
  }

  /**
   * To obtain the request config of the operation createChatCompletion
   *
   * @param createChatCompletionRequest
   * @return RequestConfig
   */
  fun createChatCompletionRequestConfig(
    createChatCompletionRequest: CreateChatCompletionRequest
  ): RequestConfig<CreateChatCompletionRequest> {
    val localVariableBody = createChatCompletionRequest
    val localVariableQuery: MultiValueMap = mutableMapOf()
    val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
    localVariableHeaders["Content-Type"] = "application/json"
    localVariableHeaders["Accept"] = "application/json"

    return RequestConfig(
      method = RequestMethod.POST,
      path = "/chat/completions",
      query = localVariableQuery,
      headers = localVariableHeaders,
      requiresAuthentication = true,
      body = localVariableBody
    )
  }

  private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
    HttpUrl.Builder()
      .scheme("http")
      .host("localhost")
      .addPathSegment(uriComponent)
      .build()
      .encodedPathSegments[0]
}
