package com.xebia.functional.openai.models.ext.chat

import com.xebia.functional.openai.models.ChatCompletionMessageToolCall
import com.xebia.functional.openai.models.ChatCompletionRequestAssistantMessageFunctionCall
import com.xebia.functional.openai.models.ChatCompletionRole
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
sealed interface ChatCompletionRequestMessage {

  fun content(): String? =
    when (this) {
      is ChatCompletionRequestAssistantMessage -> content
      is ChatCompletionRequestFunctionMessage -> content
      is ChatCompletionRequestSystemMessage -> content
      is ChatCompletionRequestToolMessage -> content
      is ChatCompletionRequestUserMessage ->
        when (content) {
          is ChatCompletionRequestUserMessageContent.ChatCompletionRequestUserMessageContentImageArray ->
            // TODO - Image array to String?
            null
          is ChatCompletionRequestUserMessageContent.ChatCompletionRequestUserMessageContentTextArray ->
            // TODO - String array to String?
            null
          is ChatCompletionRequestUserMessageContent.TextContent -> content.s
          null -> null
        }
    }

  fun role(): ChatCompletionRole =
    when (this) {
      is ChatCompletionRequestAssistantMessage -> role.asRole
      is ChatCompletionRequestFunctionMessage -> role.asRole
      is ChatCompletionRequestSystemMessage -> role.asRole
      is ChatCompletionRequestToolMessage -> role.asRole
      is ChatCompletionRequestUserMessage -> role.asRole
    }

  /**
   * @param content The contents of the system message.
   * @param role The role of the messages author, in this case `system`.
   */
  @Serializable
  data class ChatCompletionRequestSystemMessage(

    /* The contents of the system message. */
    @SerialName(value = "content") @Required val content: String?,

    /* The role of the messages author, in this case `system`. */
    @SerialName(value = "role") @Required val role: Role = Role.system
  ) : ChatCompletionRequestMessage {

    /**
     * The role of the messages author, in this case `system`.
     *
     * Values: system
     */
    @Serializable
    enum class Role(val value: String) {
      @SerialName(value = "system") system("system");

      val asRole: ChatCompletionRole = ChatCompletionRole.system
    }
  }

  /**
   * @param content
   * @param role The role of the messages author, in this case `user`.
   */
  @Serializable
  data class ChatCompletionRequestUserMessage(
    @SerialName(value = "content") @Required val content: ChatCompletionRequestUserMessageContent?,

    /* The role of the messages author, in this case `user`. */
    @SerialName(value = "role") @Required val role: Role = Role.user
  ) : ChatCompletionRequestMessage {

    /**
     * The role of the messages author, in this case `user`.
     *
     * Values: user
     */
    @Serializable
    enum class Role(val value: String) {
      @SerialName(value = "user") user("user");

      val asRole: ChatCompletionRole = ChatCompletionRole.user
    }
  }

  /**
   * @param content The contents of the assistant message.
   * @param role The role of the messages author, in this case `assistant`.
   * @param toolCalls The tool calls generated by the model, such as function calls.
   * @param functionCall
   */
  @Serializable
  data class ChatCompletionRequestAssistantMessage(

    /* The contents of the assistant message.  */
    @SerialName(value = "content") @Required val content: String?,

    /* The role of the messages author, in this case `assistant`. */
    @SerialName(value = "role") @Required val role: Role = Role.assistant,

    /* The tool calls generated by the model, such as function calls. */
    @SerialName(value = "tool_calls") val toolCalls: List<ChatCompletionMessageToolCall>? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "function_call")
    val functionCall: ChatCompletionRequestAssistantMessageFunctionCall? = null
  ) : ChatCompletionRequestMessage {

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * Values: assistant
     */
    @Serializable
    enum class Role(val value: String) {
      @SerialName(value = "assistant") assistant("assistant");

      val asRole: ChatCompletionRole = ChatCompletionRole.assistant
    }
  }

  /**
   * @param role The role of the messages author, in this case `tool`.
   * @param content The contents of the tool message.
   * @param toolCallId Tool call that this message is responding to.
   */
  @Serializable
  data class ChatCompletionRequestToolMessage(

    /* The contents of the tool message. */
    @SerialName(value = "content") @Required val content: String?,

    /* Tool call that this message is responding to. */
    @SerialName(value = "tool_call_id") @Required val toolCallId: String,

    /* The role of the messages author, in this case `tool`. */
    @SerialName(value = "role") @Required val role: Role = Role.tool
  ) : ChatCompletionRequestMessage {

    /**
     * The role of the messages author, in this case `tool`.
     *
     * Values: tool
     */
    @Serializable
    enum class Role(val value: String) {
      @SerialName(value = "tool") tool("tool");

      val asRole: ChatCompletionRole = ChatCompletionRole.tool
    }
  }

  /**
   * @param role The role of the messages author, in this case `function`.
   * @param content The return value from the function call, to return to the model.
   * @param name The name of the function to call.
   */
  @Serializable
  @Deprecated(message = "This schema is deprecated.")
  data class ChatCompletionRequestFunctionMessage(

    /* The return value from the function call, to return to the model. */
    @SerialName(value = "content") @Required val content: String?,

    /* The name of the function to call. */
    @SerialName(value = "name") @Required val name: String,

    /* The role of the messages author, in this case `function`. */
    @SerialName(value = "role") @Required val role: Role = Role.function
  ) : ChatCompletionRequestMessage {

    /**
     * The role of the messages author, in this case `function`.
     *
     * Values: function
     */
    @Serializable
    enum class Role(val value: String) {
      @SerialName(value = "function") function("function");

      val asRole: ChatCompletionRole = ChatCompletionRole.function
    }
  }
}
