package com.xebia.functional.openai.models.ext.chat

import com.xebia.functional.openai.models.ChatCompletionMessageToolCall
import com.xebia.functional.openai.models.ChatCompletionRequestAssistantMessageFunctionCall
import com.xebia.functional.openai.models.ChatCompletionRole
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param content The contents of the assistant message.
 * @param role The role of the messages author, in this case `assistant`.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param functionCall
 */
@Serializable
data class ChatCompletionRequestAssistantMessage(

  /* The contents of the assistant message.  */
  @SerialName(value = "content") @Required val content: String?,

  /* The role of the messages author, in this case `assistant`. */
  @SerialName(value = "role") @Required val role: Role,

  /* The tool calls generated by the model, such as function calls. */
  @SerialName(value = "tool_calls") val toolCalls: List<ChatCompletionMessageToolCall>?,
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "function_call")
  val functionCall: ChatCompletionRequestAssistantMessageFunctionCall?
) : ChatCompletionRequestMessage {

  constructor(content: String?) : this(content, Role.assistant, null, null)

  constructor(
    content: String?,
    toolCalls: List<ChatCompletionMessageToolCall>?
  ) : this(content, Role.assistant, toolCalls, null)

  constructor(
    content: String?,
    functionCall: ChatCompletionRequestAssistantMessageFunctionCall?
  ) : this(content, Role.assistant, null, functionCall)

  /**
   * The role of the messages author, in this case `assistant`.
   *
   * Values: assistant
   */
  @Serializable
  enum class Role(val value: String) {
    @SerialName(value = "assistant") assistant("assistant");

    val asRole: ChatCompletionRole = ChatCompletionRole.assistant
  }
}
