/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionRequestMessageContentPartTextTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ChatCompletionRequestMessageContentPartText
    // val modelInstance = ChatCompletionRequestMessageContentPartText()

    // to test the property `type` - The type of the content part.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `text` - The text content.
    should("test text") {
      // uncomment below to test the property
      // modelInstance.text shouldBe ("TODO")
    }
  }
}
