/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class ChatCompletionRequestMessageContentPartImageTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ChatCompletionRequestMessageContentPartImage
    // val modelInstance = ChatCompletionRequestMessageContentPartImage()

    // to test the property `type` - The type of the content part.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `imageUrl`
    should("test imageUrl") {
      // uncomment below to test the property
      // modelInstance.imageUrl shouldBe ("TODO")
    }
  }
}
