/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CreateAssistantRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateAssistantRequest
    // val modelInstance = CreateAssistantRequest()

    // to test the property `model`
    should("test model") {
      // uncomment below to test the property
      // modelInstance.model shouldBe ("TODO")
    }

    // to test the property `name` - The name of the assistant. The maximum length is 256
    // characters.
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `description` - The description of the assistant. The maximum length is
    // 512 characters.
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `instructions` - The system instructions that the assistant uses. The
    // maximum length is 32768 characters.
    should("test instructions") {
      // uncomment below to test the property
      // modelInstance.instructions shouldBe ("TODO")
    }

    // to test the property `tools` - A list of tool enabled on the assistant. There can be a
    // maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `retrieval`, or
    // `function`.
    should("test tools") {
      // uncomment below to test the property
      // modelInstance.tools shouldBe ("TODO")
    }

    // to test the property `fileIds` - A list of [file](/docs/api-reference/files) IDs attached to
    // this assistant. There can be a maximum of 20 files attached to the assistant. Files are
    // ordered by their creation date in ascending order.
    should("test fileIds") {
      // uncomment below to test the property
      // modelInstance.fileIds shouldBe ("TODO")
    }

    // to test the property `metadata` - Set of 16 key-value pairs that can be attached to an
    // object. This can be useful for storing additional information about the object in a
    // structured format. Keys can be a maximum of 64 characters long and values can be a maxium of
    // 512 characters long.
    should("test metadata") {
      // uncomment below to test the property
      // modelInstance.metadata shouldBe ("TODO")
    }
  }
}
