/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CreateFineTuningJobRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateFineTuningJobRequest
    // val modelInstance = CreateFineTuningJobRequest()

    // to test the property `model`
    should("test model") {
      // uncomment below to test the property
      // modelInstance.model shouldBe ("TODO")
    }

    // to test the property `trainingFile` - The ID of an uploaded file that contains training data.
    //  See [upload file](/docs/api-reference/files/upload) for how to upload a file.  Your dataset
    // must be formatted as a JSONL file. Additionally, you must upload your file with the purpose
    // `fine-tune`.  See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.
    should("test trainingFile") {
      // uncomment below to test the property
      // modelInstance.trainingFile shouldBe ("TODO")
    }

    // to test the property `hyperparameters`
    should("test hyperparameters") {
      // uncomment below to test the property
      // modelInstance.hyperparameters shouldBe ("TODO")
    }

    // to test the property `suffix` - A string of up to 18 characters that will be added to your
    // fine-tuned model name.  For example, a `suffix` of \"custom-model-name\" would produce a
    // model name like `ft:gpt-3.5-turbo:openai:custom-model-name:7p4lURel`.
    should("test suffix") {
      // uncomment below to test the property
      // modelInstance.suffix shouldBe ("TODO")
    }

    // to test the property `validationFile` - The ID of an uploaded file that contains validation
    // data.  If you provide this file, the data is used to generate validation metrics periodically
    // during fine-tuning. These metrics can be viewed in the fine-tuning results file. The same
    // data should not be present in both train and validation files.  Your dataset must be
    // formatted as a JSONL file. You must upload your file with the purpose `fine-tune`.  See the
    // [fine-tuning guide](/docs/guides/fine-tuning) for more details.
    should("test validationFile") {
      // uncomment below to test the property
      // modelInstance.validationFile shouldBe ("TODO")
    }
  }
}
