/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class CreateTranscriptionResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateTranscriptionResponse
    // val modelInstance = CreateTranscriptionResponse()

    // to test the property `text`
    should("test text") {
      // uncomment below to test the property
      // modelInstance.text shouldBe ("TODO")
    }
  }
}
