/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class ListAssistantFilesResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ListAssistantFilesResponse
    // val modelInstance = ListAssistantFilesResponse()

    // to test the property ``object``
    should("test `object`") {
      // uncomment below to test the property
      // modelInstance.`object` shouldBe ("TODO")
    }

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }

    // to test the property `firstId`
    should("test firstId") {
      // uncomment below to test the property
      // modelInstance.firstId shouldBe ("TODO")
    }

    // to test the property `lastId`
    should("test lastId") {
      // uncomment below to test the property
      // modelInstance.lastId shouldBe ("TODO")
    }

    // to test the property `hasMore`
    should("test hasMore") {
      // uncomment below to test the property
      // modelInstance.hasMore shouldBe ("TODO")
    }
  }
}
