/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class ListFineTuningJobEventsResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ListFineTuningJobEventsResponse
    // val modelInstance = ListFineTuningJobEventsResponse()

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }

    // to test the property ``object``
    should("test `object`") {
      // uncomment below to test the property
      // modelInstance.`object` shouldBe ("TODO")
    }
  }
}
