/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class MessageContentTextObjectTextTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of MessageContentTextObjectText
    // val modelInstance = MessageContentTextObjectText()

    // to test the property ``value`` - The data that makes up the text.
    should("test `value`") {
      // uncomment below to test the property
      // modelInstance.`value` shouldBe ("TODO")
    }

    // to test the property `annotations`
    should("test annotations") {
      // uncomment below to test the property
      // modelInstance.annotations shouldBe ("TODO")
    }
  }
}
