/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class MessageContentTextAnnotationsFilePathObjectFilePathTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of MessageContentTextAnnotationsFilePathObjectFilePath
    // val modelInstance = MessageContentTextAnnotationsFilePathObjectFilePath()

    // to test the property `fileId` - The ID of the file that was generated.
    should("test fileId") {
      // uncomment below to test the property
      // modelInstance.fileId shouldBe ("TODO")
    }
  }
}
