/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.models

import io.kotlintest.specs.ShouldSpec

class RunStepDetailsToolCallsObjectTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunStepDetailsToolCallsObject
    // val modelInstance = RunStepDetailsToolCallsObject()

    // to test the property `type` - Always `tool_calls`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `toolCalls` - An array of tool calls the run step was involved in. These
    // can be associated with one of three types of tools: `code_interpreter`, `retrieval`, or
    // `function`.
    should("test toolCalls") {
      // uncomment below to test the property
      // modelInstance.toolCalls shouldBe ("TODO")
    }
  }
}
