/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class CreateThreadAndRunRequestToolsInnerTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateThreadAndRunRequestToolsInner
    // val modelInstance = CreateThreadAndRunRequestToolsInner()

    // to test the property `type` - The type of tool being defined: `code_interpreter`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `function`
    should("test function") {
      // uncomment below to test the property
      // modelInstance.function shouldBe ("TODO")
    }
  }
}
