/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class CreateCompletionRequestModelTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateCompletionRequestModel
    // val modelInstance = CreateCompletionRequestModel()

  }
}
