/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class CreateModerationResponseResultsInnerTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateModerationResponseResultsInner
    // val modelInstance = CreateModerationResponseResultsInner()

    // to test the property `flagged` - Whether the content violates [OpenAI's usage
    // policies](/policies/usage-policies).
    should("test flagged") {
      // uncomment below to test the property
      // modelInstance.flagged shouldBe ("TODO")
    }

    // to test the property `categories`
    should("test categories") {
      // uncomment below to test the property
      // modelInstance.categories shouldBe ("TODO")
    }

    // to test the property `categoryScores`
    should("test categoryScores") {
      // uncomment below to test the property
      // modelInstance.categoryScores shouldBe ("TODO")
    }
  }
}
