/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class CreateChatCompletionRequestResponseFormatTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateChatCompletionRequestResponseFormat
    // val modelInstance = CreateChatCompletionRequestResponseFormat()

    // to test the property `type` - Must be one of `text` or `json_object`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }
  }
}
