/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class FineTuningJobHyperparametersTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of FineTuningJobHyperparameters
    // val modelInstance = FineTuningJobHyperparameters()

    // to test the property `nEpochs`
    should("test nEpochs") {
      // uncomment below to test the property
      // modelInstance.nEpochs shouldBe ("TODO")
    }
  }
}
