/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class MessageContentTextObjectTextAnnotationsInnerTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of MessageContentTextObjectTextAnnotationsInner
    // val modelInstance = MessageContentTextObjectTextAnnotationsInner()

    // to test the property `type` - Always `file_citation`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `text` - The text in the message content that needs to be replaced.
    should("test text") {
      // uncomment below to test the property
      // modelInstance.text shouldBe ("TODO")
    }

    // to test the property `fileCitation`
    should("test fileCitation") {
      // uncomment below to test the property
      // modelInstance.fileCitation shouldBe ("TODO")
    }

    // to test the property `startIndex`
    should("test startIndex") {
      // uncomment below to test the property
      // modelInstance.startIndex shouldBe ("TODO")
    }

    // to test the property `endIndex`
    should("test endIndex") {
      // uncomment below to test the property
      // modelInstance.endIndex shouldBe ("TODO")
    }

    // to test the property `filePath`
    should("test filePath") {
      // uncomment below to test the property
      // modelInstance.filePath shouldBe ("TODO")
    }
  }
}
