/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class RunObjectRequiredActionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunObjectRequiredAction
    // val modelInstance = RunObjectRequiredAction()

    // to test the property `type` - For now, this is always `submit_tool_outputs`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `submitToolOutputs`
    should("test submitToolOutputs") {
      // uncomment below to test the property
      // modelInstance.submitToolOutputs shouldBe ("TODO")
    }
  }
}
