/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai

import io.kotlintest.specs.ShouldSpec

class RunObjectRequiredActionSubmitToolOutputsTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunObjectRequiredActionSubmitToolOutputs
    // val modelInstance = RunObjectRequiredActionSubmitToolOutputs()

    // to test the property `toolCalls` - A list of the relevant tool calls.
    should("test toolCalls") {
      // uncomment below to test the property
      // modelInstance.toolCalls shouldBe ("TODO")
    }
  }
}
