/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class AssistantToolsFunctionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of AssistantToolsFunction
    // val modelInstance = AssistantToolsFunction()

    // to test the property `type` - The type of tool being defined: `function`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `function`
    should("test function") {
      // uncomment below to test the property
      // modelInstance.function shouldBe ("TODO")
    }
  }
}
