/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class ChatCompletionFunctionCallOptionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ChatCompletionFunctionCallOption
    // val modelInstance = ChatCompletionFunctionCallOption()

    // to test the property `name` - The name of the function to call.
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }
  }
}
