/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class CreateCompletionResponseChoicesInnerLogprobsTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CreateCompletionResponseChoicesInnerLogprobs
    // val modelInstance = CreateCompletionResponseChoicesInnerLogprobs()

    // to test the property `textOffset`
    should("test textOffset") {
      // uncomment below to test the property
      // modelInstance.textOffset shouldBe ("TODO")
    }

    // to test the property `tokenLogprobs`
    should("test tokenLogprobs") {
      // uncomment below to test the property
      // modelInstance.tokenLogprobs shouldBe ("TODO")
    }

    // to test the property `tokens`
    should("test tokens") {
      // uncomment below to test the property
      // modelInstance.tokens shouldBe ("TODO")
    }

    // to test the property `topLogprobs`
    should("test topLogprobs") {
      // uncomment below to test the property
      // modelInstance.topLogprobs shouldBe ("TODO")
    }
  }
}
