/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class ErrorTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of Error
    // val modelInstance = Error()

    // to test the property `code`
    should("test code") {
      // uncomment below to test the property
      // modelInstance.code shouldBe ("TODO")
    }

    // to test the property `message`
    should("test message") {
      // uncomment below to test the property
      // modelInstance.message shouldBe ("TODO")
    }

    // to test the property ``param``
    should("test `param`") {
      // uncomment below to test the property
      // modelInstance.`param` shouldBe ("TODO")
    }

    // to test the property `type`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }
  }
}
