/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class ImagesResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ImagesResponse
    // val modelInstance = ImagesResponse()

    // to test the property `created`
    should("test created") {
      // uncomment below to test the property
      // modelInstance.created shouldBe ("TODO")
    }

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }
  }
}
