/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class ListRunStepsResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ListRunStepsResponse
    // val modelInstance = ListRunStepsResponse()

    // to test the property ``object``
    should("test `object`") {
      // uncomment below to test the property
      // modelInstance.`object` shouldBe ("TODO")
    }

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }

    // to test the property `firstId`
    should("test firstId") {
      // uncomment below to test the property
      // modelInstance.firstId shouldBe ("TODO")
    }

    // to test the property `lastId`
    should("test lastId") {
      // uncomment below to test the property
      // modelInstance.lastId shouldBe ("TODO")
    }

    // to test the property `hasMore`
    should("test hasMore") {
      // uncomment below to test the property
      // modelInstance.hasMore shouldBe ("TODO")
    }
  }
}
