/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class ListPaginatedFineTuningJobsResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ListPaginatedFineTuningJobsResponse
    // val modelInstance = ListPaginatedFineTuningJobsResponse()

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }

    // to test the property `hasMore`
    should("test hasMore") {
      // uncomment below to test the property
      // modelInstance.hasMore shouldBe ("TODO")
    }

    // to test the property ``object``
    should("test `object`") {
      // uncomment below to test the property
      // modelInstance.`object` shouldBe ("TODO")
    }
  }
}
