/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class RunStepDetailsToolCallsCodeOutputImageObjectTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunStepDetailsToolCallsCodeOutputImageObject
    // val modelInstance = RunStepDetailsToolCallsCodeOutputImageObject()

    // to test the property `type` - Always `image`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `image`
    should("test image") {
      // uncomment below to test the property
      // modelInstance.image shouldBe ("TODO")
    }
  }
}
