/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class RunStepDetailsToolCallsCodeOutputLogsObjectTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunStepDetailsToolCallsCodeOutputLogsObject
    // val modelInstance = RunStepDetailsToolCallsCodeOutputLogsObject()

    // to test the property `type` - Always `logs`.
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `logs` - The text output from the Code Interpreter tool call.
    should("test logs") {
      // uncomment below to test the property
      // modelInstance.logs shouldBe ("TODO")
    }
  }
}
