/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import io.kotlintest.specs.ShouldSpec

class SubmitToolOutputsRunRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of SubmitToolOutputsRunRequest
    // val modelInstance = SubmitToolOutputsRunRequest()

    // to test the property `toolOutputs` - A list of tools for which the outputs are being
    // submitted.
    should("test toolOutputs") {
      // uncomment below to test the property
      // modelInstance.toolOutputs shouldBe ("TODO")
    }
  }
}
