/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param type The type of tool being defined: `function`
 * @param function
 */
@Serializable
data class AssistantToolsFunction(

  /* The type of tool being defined: `function` */
  @SerialName(value = "type") val type: AssistantToolsFunction.Type,
  @SerialName(value = "function") val function: FunctionObject
) {

  /**
   * The type of tool being defined: `function`
   *
   * Values: function
   */
  @Serializable
  enum class Type(val value: kotlin.String) {
    @SerialName(value = "function") function("function")
  }
}
