/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param content The contents of the system message.
 * @param role The role of the messages author, in this case `system`.
 * @param name An optional name for the participant. Provides the model information to differentiate
 *   between participants of the same role.
 */
@Serializable
data class ChatCompletionRequestSystemMessage(

  /* The contents of the system message. */
  @SerialName(value = "content") val content: kotlin.String,

  /* The role of the messages author, in this case `system`. */
  @SerialName(value = "role") val role: ChatCompletionRequestSystemMessage.Role,

  /* An optional name for the participant. Provides the model information to differentiate between participants of the same role. */
  @SerialName(value = "name") val name: kotlin.String? = null
) {

  /**
   * The role of the messages author, in this case `system`.
   *
   * Values: system
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "system") system("system")
  }
}
