/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param model
 * @param trainingFile The ID of an uploaded file that contains training data. See
 *   [upload file](/docs/api-reference/files/upload) for how to upload a file. Your dataset must be
 *   formatted as a JSONL file. Additionally, you must upload your file with the purpose
 *   `fine-tune`. See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.
 * @param hyperparameters
 * @param suffix A string of up to 18 characters that will be added to your fine-tuned model name.
 *   For example, a `suffix` of \"custom-model-name\" would produce a model name like
 *   `ft:gpt-3.5-turbo:openai:custom-model-name:7p4lURel`.
 * @param validationFile The ID of an uploaded file that contains validation data. If you provide
 *   this file, the data is used to generate validation metrics periodically during fine-tuning.
 *   These metrics can be viewed in the fine-tuning results file. The same data should not be
 *   present in both train and validation files. Your dataset must be formatted as a JSONL file. You
 *   must upload your file with the purpose `fine-tune`. See the
 *   [fine-tuning guide](/docs/guides/fine-tuning) for more details.
 */
@Serializable
data class CreateFineTuningJobRequest(
  @SerialName(value = "model") val model: CreateFineTuningJobRequestModel,

  /* The ID of an uploaded file that contains training data.  See [upload file](/docs/api-reference/files/upload) for how to upload a file.  Your dataset must be formatted as a JSONL file. Additionally, you must upload your file with the purpose `fine-tune`.  See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.  */
  @SerialName(value = "training_file") val trainingFile: kotlin.String,
  @SerialName(value = "hyperparameters")
  val hyperparameters: CreateFineTuningJobRequestHyperparameters? = null,

  /* A string of up to 18 characters that will be added to your fine-tuned model name.  For example, a `suffix` of \"custom-model-name\" would produce a model name like `ft:gpt-3.5-turbo:openai:custom-model-name:7p4lURel`.  */
  @SerialName(value = "suffix") val suffix: kotlin.String? = null,

  /* The ID of an uploaded file that contains validation data.  If you provide this file, the data is used to generate validation metrics periodically during fine-tuning. These metrics can be viewed in the fine-tuning results file. The same data should not be present in both train and validation files.  Your dataset must be formatted as a JSONL file. You must upload your file with the purpose `fine-tune`.  See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.  */
  @SerialName(value = "validation_file") val validationFile: kotlin.String? = null
)
