/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of the categories along with their scores as predicted by model.
 *
 * @param hate The score for the category 'hate'.
 * @param hateThreatening The score for the category 'hate/threatening'.
 * @param harassment The score for the category 'harassment'.
 * @param harassmentThreatening The score for the category 'harassment/threatening'.
 * @param selfHarm The score for the category 'self-harm'.
 * @param selfHarmIntent The score for the category 'self-harm/intent'.
 * @param selfHarmInstructions The score for the category 'self-harm/instructions'.
 * @param sexual The score for the category 'sexual'.
 * @param sexualMinors The score for the category 'sexual/minors'.
 * @param violence The score for the category 'violence'.
 * @param violenceGraphic The score for the category 'violence/graphic'.
 */
@Serializable
data class CreateModerationResponseResultsInnerCategoryScores(

  /* The score for the category 'hate'. */
  @Contextual @SerialName(value = "hate") val hate: kotlin.Double,

  /* The score for the category 'hate/threatening'. */
  @Contextual @SerialName(value = "hate/threatening") val hateThreatening: kotlin.Double,

  /* The score for the category 'harassment'. */
  @Contextual @SerialName(value = "harassment") val harassment: kotlin.Double,

  /* The score for the category 'harassment/threatening'. */
  @Contextual
  @SerialName(value = "harassment/threatening")
  val harassmentThreatening: kotlin.Double,

  /* The score for the category 'self-harm'. */
  @Contextual @SerialName(value = "self-harm") val selfHarm: kotlin.Double,

  /* The score for the category 'self-harm/intent'. */
  @Contextual @SerialName(value = "self-harm/intent") val selfHarmIntent: kotlin.Double,

  /* The score for the category 'self-harm/instructions'. */
  @Contextual @SerialName(value = "self-harm/instructions") val selfHarmInstructions: kotlin.Double,

  /* The score for the category 'sexual'. */
  @Contextual @SerialName(value = "sexual") val sexual: kotlin.Double,

  /* The score for the category 'sexual/minors'. */
  @Contextual @SerialName(value = "sexual/minors") val sexualMinors: kotlin.Double,

  /* The score for the category 'violence'. */
  @Contextual @SerialName(value = "violence") val violence: kotlin.Double,

  /* The score for the category 'violence/graphic'. */
  @Contextual @SerialName(value = "violence/graphic") val violenceGraphic: kotlin.Double
)
