/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlin.jvm.JvmInline

sealed interface CreateFineTuningJobRequestHyperparametersNEpochs {

  @JvmInline
  value class First(val value: kotlin.Int) : CreateFineTuningJobRequestHyperparametersNEpochs

  @JvmInline
  value class Second(val value: kotlin.String) : CreateFineTuningJobRequestHyperparametersNEpochs
}
