/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The hyperparameters used for the fine-tuning job. See the
 * [fine-tuning guide](/docs/guides/fine-tuning) for more details.
 *
 * @param nEpochs
 */
@Serializable
data class FineTuningJobHyperparameters(
  @SerialName(value = "n_epochs") val nEpochs: FineTuningJobHyperparametersNEpochs
)
