/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** @param fileId The ID of the file that was generated. */
@Serializable
data class MessageContentTextAnnotationsFilePathObjectFilePath(

  /* The ID of the file that was generated. */
  @SerialName(value = "file_id") val fileId: kotlin.String
)
