/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param model
 * @param name The name of the assistant. The maximum length is 256 characters.
 * @param description The description of the assistant. The maximum length is 512 characters.
 * @param instructions The system instructions that the assistant uses. The maximum length is 32768
 *   characters.
 * @param tools A list of tool enabled on the assistant. There can be a maximum of 128 tools per
 *   assistant. Tools can be of types `code_interpreter`, `retrieval`, or `function`.
 * @param fileIds A list of [File](/docs/api-reference/files) IDs attached to this assistant. There
 *   can be a maximum of 20 files attached to the assistant. Files are ordered by their creation
 *   date in ascending order. If a file was previously attached to the list but does not show up in
 *   the list, it will be deleted from the assistant.
 * @param metadata Set of 16 key-value pairs that can be attached to an object. This can be useful
 *   for storing additional information about the object in a structured format. Keys can be a
 *   maximum of 64 characters long and values can be a maxium of 512 characters long.
 */
@Serializable
data class ModifyAssistantRequest(
  @SerialName(value = "model") val model: kotlin.String? = null,

  /* The name of the assistant. The maximum length is 256 characters.  */
  @SerialName(value = "name") val name: kotlin.String? = null,

  /* The description of the assistant. The maximum length is 512 characters.  */
  @SerialName(value = "description") val description: kotlin.String? = null,

  /* The system instructions that the assistant uses. The maximum length is 32768 characters.  */
  @SerialName(value = "instructions") val instructions: kotlin.String? = null,

  /* A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `retrieval`, or `function`.  */
  @SerialName(value = "tools")
  val tools: kotlin.collections.List<AssistantObjectToolsInner>? = arrayListOf(),

  /* A list of [File](/docs/api-reference/files) IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order. If a file was previously attached to the list but does not show up in the list, it will be deleted from the assistant.  */
  @SerialName(value = "file_ids")
  val fileIds: kotlin.collections.List<kotlin.String>? = arrayListOf(),

  /* Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.  */
  @Contextual
  @SerialName(value = "metadata")
  val metadata: kotlinx.serialization.json.JsonObject? = null
)
