/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param content The contents of the assistant message.
 * @param role The role of the messages author, in this case `assistant`.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param functionCall
 */
@Serializable
data class ChatCompletionRequestAssistantMessage(

  /* The contents of the assistant message.  */
  @SerialName(value = "content") @Required val content: kotlin.String?,

  /* The role of the messages author, in this case `assistant`. */
  @SerialName(value = "role") @Required val role: ChatCompletionRequestAssistantMessage.Role,

  /* The tool calls generated by the model, such as function calls. */
  @SerialName(value = "tool_calls")
  val toolCalls: kotlin.collections.List<ChatCompletionMessageToolCall>? = null,
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "function_call")
  val functionCall: ChatCompletionRequestAssistantMessageFunctionCall? = null
) {

  /**
   * The role of the messages author, in this case `assistant`.
   *
   * Values: assistant
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "assistant") assistant("assistant")
  }
}
