/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param content
 * @param role The role of the messages author, in this case `user`.
 */
@Serializable
data class ChatCompletionRequestUserMessage(
  @SerialName(value = "content")
  @Required
  val content: com.xebia.functional.openai.models.ext.chat.ChatCompletionRequestUserMessageContent?,

  /* The role of the messages author, in this case `user`. */
  @SerialName(value = "role") @Required val role: ChatCompletionRequestUserMessage.Role
) {

  /**
   * The role of the messages author, in this case `user`.
   *
   * Values: user
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "user") user("user")
  }
}
