/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param content The return value from the function call, to return to the model.
 * @param role The role of the messages author, in this case `function`.
 * @param toolCallId Tool call that this message is responding to.
 * @param name The name of the function to call.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param functionCall
 */
@Serializable
data class ChatCompletionRequestMessage(

  /* The return value from the function call, to return to the model. */
  @SerialName(value = "content") @Required val content: kotlin.String?,

  /* The role of the messages author, in this case `function`. */
  @SerialName(value = "role") @Required val role: ChatCompletionRequestMessage.Role,

  /* Tool call that this message is responding to. */
  @SerialName(value = "tool_call_id") @Required val toolCallId: kotlin.String,

  /* The name of the function to call. */
  @SerialName(value = "name") @Required val name: kotlin.String,

  /* The tool calls generated by the model, such as function calls. */
  @SerialName(value = "tool_calls")
  val toolCalls: kotlin.collections.List<ChatCompletionMessageToolCall>? = null,
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "function_call")
  val functionCall: ChatCompletionRequestAssistantMessageFunctionCall? = null
) {

  /**
   * The role of the messages author, in this case `function`.
   *
   * Values: function
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "function") function("function")
  }
}
