/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.apis

import io.kotlintest.specs.ShouldSpec

class EmbeddingsApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EmbeddingsApi
    // val apiInstance = EmbeddingsApi()

    // to test createEmbedding
    should("test createEmbedding") {
      // uncomment below to test createEmbedding
      // val createEmbeddingRequest : CreateEmbeddingRequest =  // CreateEmbeddingRequest |
      // val result : CreateEmbeddingResponse = apiInstance.createEmbedding(createEmbeddingRequest)
      // result shouldBe ("TODO")
    }
  }
}
