/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package org.openapitools.client.apis

import io.kotlintest.specs.ShouldSpec

class ModelsApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ModelsApi
    // val apiInstance = ModelsApi()

    // to test deleteModel
    should("test deleteModel") {
      // uncomment below to test deleteModel
      // val model : kotlin.String = ft:gpt-3.5-turbo:acemeco:suffix:abc123 // kotlin.String | The
      // model to delete
      // val result : DeleteModelResponse = apiInstance.deleteModel(model)
      // result shouldBe ("TODO")
    }

    // to test listModels
    should("test listModels") {
      // uncomment below to test listModels
      // val result : ListModelsResponse = apiInstance.listModels()
      // result shouldBe ("TODO")
    }

    // to test retrieveModel
    should("test retrieveModel") {
      // uncomment below to test retrieveModel
      // val model : kotlin.String = gpt-3.5-turbo // kotlin.String | The ID of the model to use for
      // this request
      // val result : Model = apiInstance.retrieveModel(model)
      // result shouldBe ("TODO")
    }
  }
}
