package com.xebia.functional.xef.scala.prompt

package object templates {

  extension (str: String) {
    inline def writeSequenceOf(): String =
      s"""|Write a sequence of $str in the following format:
          |Step 1 - ...
          |Step 2 - ...
          |...
          |Step N - ...
      """.stripMargin

    inline def writeListOf(): String =
      s"""|Write a list of $str in the following format:
          |1. ...
          |2. ...
          |...
          |n. ...
      """.stripMargin
  }
}
