/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/** @param type The type of tool being defined: `retrieval` */
@Serializable
data class AssistantToolsRetrieval(

  /* The type of tool being defined: `retrieval` */
  @SerialName(value = "type") @Required val type: AssistantToolsRetrieval.Type
) {

  /**
   * The type of tool being defined: `retrieval`
   *
   * Values: retrieval
   */
  @Serializable
  enum class Type(val value: kotlin.String) {
    @SerialName(value = "retrieval") retrieval("retrieval")
  }
}
