/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param content The contents of the system message.
 * @param role The role of the messages author, in this case `system`.
 */
@Serializable
data class ChatCompletionRequestSystemMessage(

  /* The contents of the system message. */
  @SerialName(value = "content") @Required val content: kotlin.String?,

  /* The role of the messages author, in this case `system`. */
  @SerialName(value = "role") @Required val role: ChatCompletionRequestSystemMessage.Role
) {

  /**
   * The role of the messages author, in this case `system`.
   *
   * Values: system
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "system") system("system")
  }
}
