/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param role The role of the messages author, in this case `tool`.
 * @param content The contents of the tool message.
 * @param toolCallId Tool call that this message is responding to.
 */
@Serializable
data class ChatCompletionRequestToolMessage(

  /* The role of the messages author, in this case `tool`. */
  @SerialName(value = "role") @Required val role: ChatCompletionRequestToolMessage.Role,

  /* The contents of the tool message. */
  @SerialName(value = "content") @Required val content: kotlin.String?,

  /* Tool call that this message is responding to. */
  @SerialName(value = "tool_call_id") @Required val toolCallId: kotlin.String
) {

  /**
   * The role of the messages author, in this case `tool`.
   *
   * Values: tool
   */
  @Serializable
  enum class Role(val value: kotlin.String) {
    @SerialName(value = "tool") tool("tool")
  }
}
