/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param fileId A [File](/docs/api-reference/files) ID (with `purpose=\"assistants\"`) that the
 *   assistant should use. Useful for tools like `retrieval` and `code_interpreter` that can access
 *   files.
 */
@Serializable
data class CreateAssistantFileRequest(

  /* A [File](/docs/api-reference/files) ID (with `purpose=\"assistants\"`) that the assistant should use. Useful for tools like `retrieval` and `code_interpreter` that can access files. */
  @SerialName(value = "file_id") @Required val fileId: kotlin.String
)
