/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Log probability information for the choice.
 *
 * @param content A list of message content tokens with log probability information.
 */
@Serializable
data class CreateChatCompletionResponseChoicesInnerLogprobs(

  /* A list of message content tokens with log probability information. */
  @SerialName(value = "content")
  @Required
  val content: kotlin.collections.List<ChatCompletionTokenLogprob>?
)
