/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*

/**
 * ID of the model to use. Only `whisper-1` is currently available.
 *
 * Values: whisper_1
 */
@Serializable
enum class CreateTranscriptionRequestModel(val value: kotlin.String) {

  @SerialName(value = "whisper-1") whisper_1("whisper-1");

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use the
   * actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that the
   * client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /** Converts the provided [data] to a [String] on success, null otherwise. */
    fun encode(data: kotlin.Any?): kotlin.String? =
      if (data is CreateTranscriptionRequestModel) "$data" else null

    /** Returns a valid [CreateTranscriptionRequestModel] for [data], null otherwise. */
    fun decode(data: kotlin.Any?): CreateTranscriptionRequestModel? =
      data?.let {
        val normalizedData = "$it".lowercase()
        values().firstOrNull { value -> it == value || normalizedData == "$value".lowercase() }
      }
  }
}
