/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*

/**
 * The name of the model to fine-tune. You can select one of the
 * [supported models](/docs/guides/fine-tuning/what-models-can-be-fine-tuned).
 *
 * Values: babbage_002,davinci_002,gpt_3_5_turbo
 */
@Serializable
enum class CreateFineTuningJobRequestModel(val value: kotlin.String) {

  @SerialName(value = "babbage-002") babbage_002("babbage-002"),
  @SerialName(value = "davinci-002") davinci_002("davinci-002"),
  @SerialName(value = "gpt-3.5-turbo") gpt_3_5_turbo("gpt-3.5-turbo");

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use the
   * actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that the
   * client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /** Converts the provided [data] to a [String] on success, null otherwise. */
    fun encode(data: kotlin.Any?): kotlin.String? =
      if (data is CreateFineTuningJobRequestModel) "$data" else null

    /** Returns a valid [CreateFineTuningJobRequestModel] for [data], null otherwise. */
    fun decode(data: kotlin.Any?): CreateFineTuningJobRequestModel? =
      data?.let {
        val normalizedData = "$it".lowercase()
        values().firstOrNull { value -> it == value || normalizedData == "$value".lowercase() }
      }
  }
}
