/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*

/**
 * The model to use for image generation. Only `dall-e-2` is supported at this time.
 *
 * Values: dall_e_2
 */
@Serializable
enum class CreateImageEditRequestModel(val value: kotlin.String) {

  @SerialName(value = "dall-e-2") dall_e_2("dall-e-2");

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use the
   * actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that the
   * client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /** Converts the provided [data] to a [String] on success, null otherwise. */
    fun encode(data: kotlin.Any?): kotlin.String? =
      if (data is CreateImageEditRequestModel) "$data" else null

    /** Returns a valid [CreateImageEditRequestModel] for [data], null otherwise. */
    fun decode(data: kotlin.Any?): CreateImageEditRequestModel? =
      data?.let {
        val normalizedData = "$it".lowercase()
        values().firstOrNull { value -> it == value || normalizedData == "$value".lowercase() }
      }
  }
}
