/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Deletes the association between the assistant and the file, but does not delete the
 * [File](/docs/api-reference/files) object itself.
 *
 * @param id
 * @param deleted
 * @param `object`
 */
@Serializable
data class DeleteAssistantFileResponse(
  @SerialName(value = "id") @Required val id: kotlin.String,
  @SerialName(value = "deleted") @Required val deleted: kotlin.Boolean,
  @SerialName(value = "object") @Required val `object`: DeleteAssistantFileResponse.`Object`
) {

  /** Values: assistantPeriodFilePeriodDeleted */
  @Serializable
  enum class `Object`(val value: kotlin.String) {
    @SerialName(value = "assistant.file.deleted")
    assistantPeriodFilePeriodDeleted("assistant.file.deleted")
  }
}
