/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param message 
 * @param `param` 
 * @param type 
 */
@Serializable

data class Error (

    @SerialName(value = "code") @Required val code: kotlin.String?,

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "param") @Required val `param`: kotlin.String?,

    @SerialName(value = "type") @Required val type: kotlin.String

)

