/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.MessageObjectContentInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Represents a message within a [thread](/docs/api-reference/threads).
 *
 * @param id The identifier, which can be referenced in API endpoints.
 * @param `object` The object type, which is always `thread.message`.
 * @param createdAt The Unix timestamp (in seconds) for when the message was created.
 * @param threadId The [thread](/docs/api-reference/threads) ID that this message belongs to.
 * @param role The entity that produced the message. One of `user` or `assistant`.
 * @param content The content of the message in array of text and/or images.
 * @param assistantId If applicable, the ID of the [assistant](/docs/api-reference/assistants) that authored this message.
 * @param runId If applicable, the ID of the [run](/docs/api-reference/runs) associated with the authoring of this message.
 * @param fileIds A list of [file](/docs/api-reference/files) IDs that the assistant should use. Useful for tools like retrieval and code_interpreter that can access files. A maximum of 10 files can be attached to a message.
 * @param metadata Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
 */
@Serializable

data class MessageObject (

    /* The identifier, which can be referenced in API endpoints. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The object type, which is always `thread.message`. */
    @SerialName(value = "object") @Required val `object`: MessageObject.`Object`,

    /* The Unix timestamp (in seconds) for when the message was created. */
    @SerialName(value = "created_at") @Required val createdAt: kotlin.Int,

    /* The [thread](/docs/api-reference/threads) ID that this message belongs to. */
    @SerialName(value = "thread_id") @Required val threadId: kotlin.String,

    /* The entity that produced the message. One of `user` or `assistant`. */
    @SerialName(value = "role") @Required val role: MessageObject.Role,

    /* The content of the message in array of text and/or images. */
    @SerialName(value = "content") @Required val content: kotlin.collections.List<MessageObjectContentInner>,

    /* If applicable, the ID of the [assistant](/docs/api-reference/assistants) that authored this message. */
    @SerialName(value = "assistant_id") @Required val assistantId: kotlin.String?,

    /* If applicable, the ID of the [run](/docs/api-reference/runs) associated with the authoring of this message. */
    @SerialName(value = "run_id") @Required val runId: kotlin.String?,

    /* A list of [file](/docs/api-reference/files) IDs that the assistant should use. Useful for tools like retrieval and code_interpreter that can access files. A maximum of 10 files can be attached to a message. */
    @SerialName(value = "file_ids") @Required val fileIds: kotlin.collections.List<kotlin.String> = arrayListOf(),

    /* Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.  */
    @SerialName(value = "metadata") @Required val metadata: kotlin.String?

) {

    /**
     * The object type, which is always `thread.message`.
     *
     * Values: threadPeriodMessage
     */
    @Serializable
    enum class `Object`(val value: kotlin.String) {
        @SerialName(value = "thread.message") threadPeriodMessage("thread.message");
    }
    /**
     * The entity that produced the message. One of `user` or `assistant`.
     *
     * Values: user,assistant
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "user") user("user"),
        @SerialName(value = "assistant") assistant("assistant");
    }
}

