/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.MessageContentTextAnnotationsFilePathObjectFilePath

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A URL for the file that's generated when the assistant used the `code_interpreter` tool to generate a file.
 *
 * @param type Always `file_path`.
 * @param text The text in the message content that needs to be replaced.
 * @param filePath 
 * @param startIndex 
 * @param endIndex 
 */
@Serializable

data class MessageContentTextAnnotationsFilePathObject (

    /* Always `file_path`. */
    @SerialName(value = "type") @Required val type: MessageContentTextAnnotationsFilePathObject.Type,

    /* The text in the message content that needs to be replaced. */
    @SerialName(value = "text") @Required val text: kotlin.String,

    @SerialName(value = "file_path") @Required val filePath: MessageContentTextAnnotationsFilePathObjectFilePath,

    @SerialName(value = "start_index") @Required val startIndex: kotlin.Int,

    @SerialName(value = "end_index") @Required val endIndex: kotlin.Int

) {

    /**
     * Always `file_path`.
     *
     * Values: filePath
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "file_path") filePath("file_path");
    }
}

