/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param fileId The [File](/docs/api-reference/files) ID of the image in the message content.
 */
@Serializable

data class MessageContentImageFileObjectImageFile (

    /* The [File](/docs/api-reference/files) ID of the image in the message content. */
    @SerialName(value = "file_id") @Required val fileId: kotlin.String

)

