/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/** @param fileId The ID of the file that was generated. */
@Serializable
data class MessageContentTextAnnotationsFilePathObjectFilePath(

  /* The ID of the file that was generated. */
  @SerialName(value = "file_id") @Required val fileId: kotlin.String
)
