/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The `File` object represents a document that has been uploaded to OpenAI.
 *
 * @param id The file identifier, which can be referenced in the API endpoints.
 * @param bytes The size of the file, in bytes.
 * @param createdAt The Unix timestamp (in seconds) for when the file was created.
 * @param filename The name of the file.
 * @param `object` The object type, which is always `file`.
 * @param purpose The intended purpose of the file. Supported values are `fine-tune`,
 *   `fine-tune-results`, `assistants`, and `assistants_output`.
 * @param status Deprecated. The current status of the file, which can be either `uploaded`,
 *   `processed`, or `error`.
 * @param statusDetails Deprecated. For details on why a fine-tuning training file failed
 *   validation, see the `error` field on `fine_tuning.job`.
 */
@Serializable
data class OpenAIFile(

  /* The file identifier, which can be referenced in the API endpoints. */
  @SerialName(value = "id") @Required val id: kotlin.String,

  /* The size of the file, in bytes. */
  @SerialName(value = "bytes") @Required val bytes: kotlin.Int,

  /* The Unix timestamp (in seconds) for when the file was created. */
  @SerialName(value = "created_at") @Required val createdAt: kotlin.Int,

  /* The name of the file. */
  @SerialName(value = "filename") @Required val filename: kotlin.String,

  /* The object type, which is always `file`. */
  @SerialName(value = "object") @Required val `object`: OpenAIFile.`Object`,

  /* The intended purpose of the file. Supported values are `fine-tune`, `fine-tune-results`, `assistants`, and `assistants_output`. */
  @SerialName(value = "purpose") @Required val purpose: OpenAIFile.Purpose,

  /* Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`. */
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "status")
  @Required
  val status: OpenAIFile.Status,

  /* Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`. */
  @Deprecated(message = "This property is deprecated.")
  @SerialName(value = "status_details")
  val statusDetails: kotlin.String? = null
) {

  /**
   * The object type, which is always `file`.
   *
   * Values: file
   */
  @Serializable
  enum class `Object`(val value: kotlin.String) {
    @SerialName(value = "file") file("file")
  }
  /**
   * The intended purpose of the file. Supported values are `fine-tune`, `fine-tune-results`,
   * `assistants`, and `assistants_output`.
   *
   * Values: fineMinusTune,fineMinusTuneMinusResults,assistants,assistantsOutput
   */
  @Serializable
  enum class Purpose(val value: kotlin.String) {
    @SerialName(value = "fine-tune") fineMinusTune("fine-tune"),
    @SerialName(value = "fine-tune-results") fineMinusTuneMinusResults("fine-tune-results"),
    @SerialName(value = "assistants") assistants("assistants"),
    @SerialName(value = "assistants_output") assistantsOutput("assistants_output")
  }
  /**
   * Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or
   * `error`.
   *
   * Values: uploaded,processed,error
   */
  @Serializable
  enum class Status(val value: kotlin.String) {
    @SerialName(value = "uploaded") uploaded("uploaded"),
    @SerialName(value = "processed") processed("processed"),
    @SerialName(value = "error") error("error")
  }
}
