/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/** @param messageId The ID of the message that was created by this run step. */
@Serializable
data class RunStepDetailsMessageCreationObjectMessageCreation(

  /* The ID of the message that was created by this run step. */
  @SerialName(value = "message_id") @Required val messageId: kotlin.String
)
