/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.RunStepDetailsToolCallsCodeObjectCodeInterpreter

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Details of the Code Interpreter tool call the run step was involved in.
 *
 * @param id The ID of the tool call.
 * @param type The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
 * @param codeInterpreter 
 */
@Serializable

data class RunStepDetailsToolCallsCodeObject (

    /* The ID of the tool call. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The type of tool call. This is always going to be `code_interpreter` for this type of tool call. */
    @SerialName(value = "type") @Required val type: RunStepDetailsToolCallsCodeObject.Type,

    @SerialName(value = "code_interpreter") @Required val codeInterpreter: RunStepDetailsToolCallsCodeObjectCodeInterpreter

) {

    /**
     * The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
     *
     * Values: codeInterpreter
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "code_interpreter") codeInterpreter("code_interpreter");
    }
}

