/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * @param id The ID of the tool call object.
 * @param type The type of tool call. This is always going to be `retrieval` for this type of tool
 *   call.
 * @param retrieval For now, this is always going to be an empty object.
 */
@Serializable
data class RunStepDetailsToolCallsRetrievalObject(

  /* The ID of the tool call object. */
  @SerialName(value = "id") @Required val id: kotlin.String,

  /* The type of tool call. This is always going to be `retrieval` for this type of tool call. */
  @SerialName(value = "type") @Required val type: RunStepDetailsToolCallsRetrievalObject.Type,

  /* For now, this is always going to be an empty object. */
  @SerialName(value = "retrieval") val retrieval: kotlinx.serialization.json.JsonObject? = null
) {

  /**
   * The type of tool call. This is always going to be `retrieval` for this type of tool call.
   *
   * Values: retrieval
   */
  @Serializable
  enum class Type(val value: kotlin.String) {
    @SerialName(value = "retrieval") retrieval("retrieval")
  }
}
