/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.RunStepDetailsToolCallsCodeOutputImageObjectImage

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type Always `image`.
 * @param image 
 */
@Serializable

data class RunStepDetailsToolCallsCodeOutputImageObject (

    /* Always `image`. */
    @SerialName(value = "type") @Required val type: RunStepDetailsToolCallsCodeOutputImageObject.Type,

    @SerialName(value = "image") @Required val image: RunStepDetailsToolCallsCodeOutputImageObjectImage

) {

    /**
     * Always `image`.
     *
     * Values: image
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "image") image("image");
    }
}

