/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Text output from the Code Interpreter tool call as part of a run step.
 *
 * @param type Always `logs`.
 * @param logs The text output from the Code Interpreter tool call.
 */
@Serializable

data class RunStepDetailsToolCallsCodeOutputLogsObject (

    /* Always `logs`. */
    @SerialName(value = "type") @Required val type: RunStepDetailsToolCallsCodeOutputLogsObject.Type,

    /* The text output from the Code Interpreter tool call. */
    @SerialName(value = "logs") @Required val logs: kotlin.String

) {

    /**
     * Always `logs`.
     *
     * Values: logs
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "logs") logs("logs");
    }
}

