/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.RunStepDetailsToolCallsCodeOutputImageObject
import com.xebia.functional.openai.models.RunStepDetailsToolCallsCodeOutputImageObjectImage
import com.xebia.functional.openai.models.RunStepDetailsToolCallsCodeOutputLogsObject

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type Always `logs`.
 * @param logs The text output from the Code Interpreter tool call.
 * @param image 
 */
@Serializable

data class RunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsInner (

    /* Always `logs`. */
    @SerialName(value = "type") @Required val type: RunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsInner.Type,

    /* The text output from the Code Interpreter tool call. */
    @SerialName(value = "logs") @Required val logs: kotlin.String,

    @SerialName(value = "image") @Required val image: RunStepDetailsToolCallsCodeOutputImageObjectImage

) {

    /**
     * Always `logs`.
     *
     * Values: logs,image
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "logs") logs("logs"),
        @SerialName(value = "image") image("image");
    }
}

