/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xebia.functional.openai.models

import com.xebia.functional.openai.models.SubmitToolOutputsRunRequestToolOutputsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param toolOutputs A list of tools for which the outputs are being submitted.
 */
@Serializable

data class SubmitToolOutputsRunRequest (

    /* A list of tools for which the outputs are being submitted. */
    @SerialName(value = "tool_outputs") @Required val toolOutputs: kotlin.collections.List<SubmitToolOutputsRunRequestToolOutputsInner>

)

