/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import io.kotlintest.specs.ShouldSpec

class DeleteAssistantResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of DeleteAssistantResponse
    // val modelInstance = DeleteAssistantResponse()

    // to test the property `id`
    should("test id") {
      // uncomment below to test the property
      // modelInstance.id shouldBe ("TODO")
    }

    // to test the property `deleted`
    should("test deleted") {
      // uncomment below to test the property
      // modelInstance.deleted shouldBe ("TODO")
    }

    // to test the property ``object``
    should("test `object`") {
      // uncomment below to test the property
      // modelInstance.`object` shouldBe ("TODO")
    }
  }
}
