/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.xebia.functional.openai.models

import io.kotlintest.specs.ShouldSpec

class RunStepDetailsToolCallsCodeOutputImageObjectImageTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RunStepDetailsToolCallsCodeOutputImageObjectImage
    // val modelInstance = RunStepDetailsToolCallsCodeOutputImageObjectImage()

    // to test the property `fileId` - The [file](/docs/api-reference/files) ID of the image.
    should("test fileId") {
      // uncomment below to test the property
      // modelInstance.fileId shouldBe ("TODO")
    }
  }
}
