name: Build

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        include:
          - platform: jvm
            os: ubuntu-latest
          - platform: js
            os: ubuntu-latest
          - platform: linuxX64
            os: ubuntu-latest
          - platform: macosX64
            os: macos-latest
          - platform: mingwX64
            os: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Test (multip/no Windows)
        run: ./gradlew buildAndTestMultip -Pplatform=${{ matrix.platform }} -PgradleCommand=./gradlew
        if: ${{ matrix.platform != 'mingwX64' }}

      - name: Build and Test (multip/Windows)
        run: cmd.exe /c gradlew.bat buildAndTestMultip -Pplatform=${{ matrix.platform }} -PgradleCommand='gradlew.bat'
        if: ${{ matrix.platform == 'mingwX64' }}

      - name: Build and Test (singlep/No Windows)
        run: ./gradlew buildAndTestSinglep -PgradleCommand=./gradlew
        if: ${{ matrix.platform == 'jvm' && matrix.platform != 'mingwX64' }}

      - name: Build and Test (singlep/Windows)
        run: ./gradlew buildAndTestSinglep -PgradleCommand='gradlew.bat'
        if: ${{ matrix.platform == 'jvm' && matrix.platform == 'mingwX64' }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports'
          path: '**/build/reports/**'
