name: Build

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        platform: [ jvm, js, linuxX64, macosX64, mingwX64 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Multi-platform Modules
        run: |
          ./gradlew \
            :xef-core:${{ matrix.platform }}Test \
            :xef-filesystem:${{ matrix.platform }}Test \
            :xef-tokenizer:${{ matrix.platform }}Test \
            :xef-kotlin:${{ matrix.platform }}Test

      - name: Build Single-platform Modules
        if: matrix.platform == 'jvm'
        run: |
          ./gradlew \
            :xef-lucene:build \
            :xef-pdf:build \
            :xef-postgresql:build \
            :xef-sql:build \
            :xef-kotlin-examples:build \
            :kotlin-loom:build \
            :xef-scala-examples:build \
            :xef-scala:build \
            :xef-scala-cats:build

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports'
          path: '**/build/reports/**'
