name: Build

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        include:
          - platform: jvm
            os: ubuntu-latest
          - platform: js
            os: ubuntu-latest
          - platform: linuxX64
            os: ubuntu-latest
          - platform: macosX64
            os: macos-latest
          - platform: mingwX64
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Build and Test (multip)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildAndTestMultip -Pplatform=${{ matrix.platform }}

      - name: Build and Test (singlep)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildAndTestSinglep -Pplatform=${{ matrix.platform }}
        if: ${{ matrix.platform == 'jvm' }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports'
          path: '**/build/reports/**'
