name: Generate and deploy GitHub Pages

on:
  release:
    types: [published]

jobs:
  githubpages:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dokka
        id: Dokka
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} dokkaHtml

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
