name: Publish final version

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  OSS_USER: '${{ secrets.OSS_USER }}'
  OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
  OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
  SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
  SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'

jobs:
  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Publish final version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToSonatype closeSonatypeStagingRepository
