name: "Publish SNAPSHOT"

on:
  push:
    branches:
      - main

env:
  OSS_USER: '${{ secrets.OSS_USER }}'
  OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
  SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
  SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'

jobs:
  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble -x:kotlin-loom:assemble

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Publish final version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=0.0.1-SNAPSHOT publishToSonatype -x:kotlin-loom:publishToSonatype

  publish-kotlin-loom:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - name: assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :kotlin-loom:assemble -Pversion=${{ inputs.version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Publish final version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=0.0.1-SNAPSHOT :kotlin-loom:publishToSonatype
